databases:
  - name: pintorescobubble
    databaseName: pintorescobubble
    user: pintorescobubble
    plan: free

services:
  - type: web
    name: mysite
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pintorescobubble
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false